harnessApiVersion: '1.0'
type: INFRA_DEFINITION
cloudProviderType: KUBERNETES_CLUSTER
deploymentType: KUBERNETES
infrastructure:
- type: DIRECT_KUBERNETES
  cloudProviderName: qa-kubernetes_cluster
  namespace: ${workflow.variables.namespace}
  releaseName: release-${infra.kubernetes.infraId}
