harnessApiVersion: '1.0'
type: ROLLING
concurrencyStrategy: INFRA
envName: dev
failureStrategies:
- executionScope: WORKFLOW
  failureTypes:
  - APPLICATION_ERROR
  repairActionCode: ROLLBACK_WORKFLOW
  retryCount: 0
notificationRules:
- conditions:
  - FAILED
  executionScope: WORKFLOW
  notificationGroupAsExpression: false
  userGroupAsExpression: false
  userGroupIds:
  - yQo3j5AvTwWgA4zmojRntg
phases:
- type: KUBERNETES
  computeProviderName: qa-kubernetes_cluster
  daemonSet: false
  infraDefinitionName: Dev
  name: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    steps:
    - type: K8S_DEPLOYMENT_ROLLING
      name: Rollout Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Verify
    steps:
    - type: APP_DYNAMICS
      name: AppDynamics
      properties:
        analysisTolerance: LOW
        comparisonStrategy: COMPARE_WITH_PREVIOUS
        executeWithPreviousSteps: false
        templateExpressions:
        - expression: ${AppDynamics_Server}
          fieldName: analysisServerConfigId
          metadata:
            entityType: APPDYNAMICS_CONFIGID
            relatedField: ${AppDynamics_Application}
        - expression: ${AppDynamics_Application}
          fieldName: applicationId
          metadata:
            entityType: APPDYNAMICS_APPID
            relatedField: ${AppDynamics_Tier}
        - expression: ${AppDynamics_Tier}
          fieldName: tierId
          metadata:
            entityType: APPDYNAMICS_TIERID
            relatedField: ''
        templateUuid: null
        templateVariables: null
        templateVersion: null
        timeDuration: 15
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: SampleK8s
  statefulSet: false
  templateExpressions:
  - expression: ${Service}
    fieldName: serviceId
    metadata:
    - name: relatedField
      value: ${InfraDefinition_KUBERNETES}
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: SERVICE
  - expression: ${InfraDefinition_KUBERNETES}
    fieldName: infraDefinitionId
    metadata:
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
rollbackPhases:
- type: KUBERNETES
  computeProviderName: qa-kubernetes_cluster
  daemonSet: false
  infraDefinitionName: Dev
  name: Rollback Rolling
  phaseNameForRollback: Rolling
  phaseSteps:
  - type: K8S_PHASE_STEP
    name: Deploy
    phaseStepNameForRollback: Deploy
    statusForRollback: SUCCESS
    steps:
    - type: K8S_DEPLOYMENT_ROLLING_ROLLBACK
      name: Rollback Deployment
    stepsInParallel: false
  - type: K8S_PHASE_STEP
    name: Wrap Up
    phaseStepNameForRollback: Wrap Up
    stepsInParallel: false
  provisionNodes: false
  serviceName: SampleK8s
  statefulSet: false
  templateExpressions:
  - expression: ${Service}
    fieldName: serviceId
    metadata:
    - name: relatedField
      value: ${InfraDefinition_KUBERNETES}
    - name: artifactType
      value: DOCKER
    - name: entityType
      value: SERVICE
  - expression: ${InfraDefinition_KUBERNETES}
    fieldName: infraDefinitionId
    metadata:
    - name: relatedField
    - name: entityType
      value: INFRASTRUCTURE_DEFINITION
tags:
  ${account.defaults.example}: ''
  ${app.defaults.RUNTIME_PATH}: ''
  ${workflow.variables.wfvar}: ''
  WorkflowVar: ${workflow.variables.wfvar}
templateExpressions:
- expression: ${Environment}
  fieldName: envId
  metadata:
  - name: relatedField
    value: ${InfraDefinition_KUBERNETES}
  - name: entityType
    value: ENVIRONMENT
- expression: ${Service}
  fieldName: serviceId
  metadata:
  - name: relatedField
    value: ${InfraDefinition_KUBERNETES}
  - name: artifactType
    value: DOCKER
  - name: entityType
    value: SERVICE
- expression: ${InfraDefinition_KUBERNETES}
  fieldName: infraDefinitionId
  metadata:
  - name: relatedField
  - name: entityType
    value: INFRASTRUCTURE_DEFINITION
templatized: true
userVariables:
- type: ENTITY
  description: Variable for Environment entity
  fixed: false
  mandatory: true
  name: Environment
- type: ENTITY
  description: Variable for Service entity in Rollback Rolling
  fixed: false
  mandatory: true
  name: Service
- type: ENTITY
  description: Variable for Infrastructure Definition entity in Rollback Rolling
  fixed: false
  mandatory: true
  name: InfraDefinition_KUBERNETES
- type: ENTITY
  description: Variable for AppDynamics Server entity in AppDynamics
  fixed: false
  mandatory: true
  name: AppDynamics_Server
- type: ENTITY
  description: Variable for AppDynamics Application entity in AppDynamics
  fixed: false
  mandatory: true
  name: AppDynamics_Application
- type: ENTITY
  description: Variable for AppDynamics Tier entity in AppDynamics
  fixed: false
  mandatory: true
  name: AppDynamics_Tier
- type: TEXT
  fixed: false
  mandatory: true
  name: wfvar
  value: wf-var-value
- type: TEXT
  fixed: false
  mandatory: false
  name: dash-dash
  value: dash-value
